fileVersion: 1
id: "3"
mappingDefinitions:
  RMH_ACTIVE_CAMPAIGN_RAW:
    database: RMH_RAW
    schema: ACTIVECAMPAIGN
  RMH_CLOCKIFY_RAW:
    database: RMH_RAW
    schema: CLOCKIFY
  RMH_DROPBOX_RAW:
    database: RMH_RAW
    schema: DROPBOX
  RMH_FINANCE_INT:
    database: RMH_PROD
    schema: RMH_FINANCE_INT
  RMH_FINANCE_MODEL_GOLD:
    database: RMH_PROD
    schema: RMH_FINANCE_MODEL_GOLD
  RMH_GOOGLE_ANALYTICS_RAW:
    database: RMH_RAW
    schema: GOOGLE_ANALYTICS_4
  RMH_MARKETING_GOLD:
    database: RMH_PROD
    schema: RMH_MARKETING_GOLD
  RMH_MARKETING_INT:
    database: RMH_PROD
    schema: RMH_MARKETING_INT
  RMH_MONDAY_RAW:
    database: RMH_RAW
    schema: MONDAY
  RMH_SPIRO_RAW:
    database: RMH_RAW
    schema: SPIRO
  RMH_SPIRO_STG:
    database: RMH_PROD
    schema: RMH_SPIRO_STG
  RMH_SQL_SERVER_SERVICE_RAW:
    database: RMH_RAW
    schema: SQL_SERVER_DBO
  RMH_SQL_SERVER_SERVICE_STG:
    database: RMH_PROD
    schema: RMH_SQL_SERVER_SERVICE_STG
name: Production
type: Environment
