fileVersion: 1
id: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
name: AUTOMATION
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: RMH_ACTIVE_CAMPAIGN_RAW
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 8212445b-3da1-4383-9418-60fe343d7acf
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: ID
        nullable: false
        primaryKey: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 26ce699a-3d19-4413-a405-56fec535198b
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: USER_ID
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 1eb30b1c-4da0-4e97-8ae6-f1233248ff6f
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: DEFAULT_SCREENSHOT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b54aad0b-01ef-4ae7-9b3e-c59062acd6b6
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 1f0e2620-1e6a-4b0c-ad25-2c70e0bb45d1
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: ENTITLEMENTS_VIOLATION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 8d2285a5-d641-48f3-9c8a-9177534b39da
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: STATUS
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 6003f9f7-5307-4ff6-8c37-16b79666a118
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: SCREENSHOT
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 64709c3a-5968-4d00-a8d4-680eaa3cebe6
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: HIDDEN
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: b36f00cb-1c3f-4c9e-a2ca-c57a80dce912
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: EXITED
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 0ac79779-161a-43c0-84d7-b161ffa0d264
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: VARCHAR(256)
        defaultValue: ""
        description: ""
        name: ENTERED
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 617381e6-f1f0-4129-afa9-d1811918c04e
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: BOOLEAN
        defaultValue: ""
        description: ""
        name: _FIVETRAN_DELETED
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: a253a215-bfbf-4ac4-ae3d-491e772a7943
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: TIMESTAMP_TZ(9)
        defaultValue: ""
        description: ""
        name: _FIVETRAN_SYNCED
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: dd252dc6-72c4-4e89-817f-c520fa5876c0
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: TIMESTAMP_TZ(9)
        defaultValue: ""
        description: ""
        name: M_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: a1cd177a-40be-4d4d-8c65-6536c0a052d6
          stepCounter: cba1c5cd-ce82-4874-91fe-fc99b63efe2e
        config: {}
        dataType: TIMESTAMP_TZ(9)
        defaultValue: ""
        description: ""
        name: C_DATE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
  name: AUTOMATION
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
